### ISSUE TITLE
Line intersection links broken

### ISSUE THREAD

**Issue by radi-cho** [RSG-Group/website#1]
![image](https://user-images.githubusercontent.com/12954909/29996617-7737a5d2-900a-11e7-97ec-9f94d0ce571e.png)

**Comment by retrixe** [comment]
Confirmed, duplicate. The appropriate changes have been made post deployment on master.

**Comment by retrixe** [comment]
Will push this with newer responsive images for Chess and intersection. Will close from there.

**Comment by radi-cho** [comment]
Okay
