### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by radi-cho** [RSG-Group/website#17]
![image](https://user-images.githubusercontent.com/12954909/31627842-6525c2f0-b2b7-11e7-9d70-cad12f2ef16f.png)

**Comment by retrixe** [comment]
I didn't do no deploy

**Comment by retrixe** [comment]
This was working just now? .-.

**Comment by retrixe** [comment]
Uh, it seems like it's working for me ._.

**Comment by retrixe** [comment]
Can't do anything right now, it should work after a restart after deployment goes to sleep. It will because it goes to sleep every hour or so. Should be online tomorrow.

**Comment by radi-cho** [comment]
# @retrixe, WHAT'S HAPPENING?!?

![image](https://user-images.githubusercontent.com/12954909/31832331-514d273a-b5cf-11e7-83e5-303f9a5b47c4.png)

**Comment by retrixe** [comment]
It will take another 7 days to resolve the issue smh
Perhaps.. we could do this faster though. I will see tomorrow, because I have a computer right now though it does not have now-cli installed.

**Comment by retrixe** [comment]
Fixed, closed, sincerely apologize for downtime.
