### ISSUE TITLE
Wrong image alts

### ISSUE THREAD

**Issue by radi-cho** [RSG-Group/website#2]
![image](https://user-images.githubusercontent.com/12954909/29996656-30de643a-900b-11e7-8e74-a5ba488c5a1a.png)

**Comment by radi-cho** [comment]
No worries. I'll fix this.

**Comment by retrixe** [comment]
Confirmed, resolved. I'll be deploying fixes to this and #1 now.

**Comment by retrixe** [comment]
Will push this with newer responsive images for Chess and intersection. Will close from there.

**Comment by radi-cho** [comment]
Cool
