### ISSUE TITLE
The website can't load the resources (on my side)

### ISSUE THREAD

**Issue by radi-cho** [RSG-Group/website#6]
![image](https://user-images.githubusercontent.com/12954909/30201278-da8d12bc-9482-11e7-95e9-dbb1a95ce71b.png)

Edit by @retrixe: This now covers the service worker and its cache interfering with updates to `website`.

**Comment by retrixe** [comment]
Confirmed.

**Comment by radi-cho** [comment]
Yes. I'm closing this... If there are problem reopen it.

**Comment by retrixe** [comment]
The service worker needs some work, associated with this issue.

**Comment by radi-cho** [comment]
Okay
